# Generated by Django 3.2.4 on 2021-12-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
        ('wishlists', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gift_given',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_given', to='gifts.gift'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gift_received',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_received', to='gifts.gift'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlist_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_owner', to='wishlists.wishlist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlist_sender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_sender', to='wishlists.wishlist'),
        ),
    ]
